### ISSUE TITLE
How to filter duplicate data after sending data

### ISSUE THREAD

**Issue by 1455132351** [edgexfoundry/edgex-examples#47] opened 2021-06-01 09:00 UTC

**Comment by jpwhitemn** [comment] 2021-06-08 20:40
Google Translate of original title:  数据发送到edgex后如何过滤重复数据 is:  How to filter duplicate data after sending data to edgex

**Comment by jpwhitemn** [comment] 2021-06-08 20:41
duplicate of #48

**Closed by jpwhitemn** 2021-06-08 20:41 UTC
