### ISSUE TITLE
Fail to use usb-camera with evam

### ISSUE THREAD

**Issue by Ianzhou397** [edgexfoundry/edgex-examples#216] opened 2023-05-23 02:54 UTC

**Comment by Ianzhou397** [comment] 2023-05-23 03:01
![image](https://github.com/edgexfoundry/edgex-examples/assets/107825627/82caee22-95fd-40a5-8112-ade940af5a73)

As shown in the figure, the MQTT service seems to be unusable, but I have configured it according to the technical documentation. I think it's possible that the inference data stream can't be delivered to edgex via MQTT. How can this situation be improved?

**Comment by presatish** [comment] 2023-05-23 17:19
@Ianzhou397 We are facing some issues with the latest usb service and the sample app and we are looking into resolving them. But your issues seem to be different, you should not be facing any mqtt related issues. Can you please share which branch/version of sample app and edgex-compose you are using?

**Comment by Ianzhou397** [comment] 2023-05-24 02:20
When I followed the steps in the article, I found that the USB camera needs to register the device manually, otherwise there is no device at all in the 59750 page, and there is no device in the 4000. So I manually registered the device, but when I turned on the data flow, I found that an error was reported and the device and the service could not communicate.
In addition, edgex-compose I use levski, the default branch for the sample app.
![image](https://github.com/edgexfoundry/edgex-examples/assets/107825627/448801f3-9f90-4f5d-896d-4a66d4d8e962)
![image](https://github.com/edgexfoundry/edgex-examples/assets/107825627/b90c5f53-d0fc-44f3-9f55-d4f4214921e7)
![image](https://github.com/edgexfoundry/edgex-examples/assets/107825627/c952b99c-94f8-48ca-98c0-d030b8ed841a)

Here is my reference URL
https://docs.edgexfoundry.org/2.3/examples/Ch-ExamplesUsbDeviceService/
https://github.com/edgexfoundry/edgex-examples/blob/main/application-services/custom/camera-management/README.md

**Comment by Ianzhou397** [comment] 2023-05-24 13:45
I reproduced the documentation and encountered the following error：
![image](https://github.com/edgexfoundry/edgex-examples/assets/107825627/c56d17d9-51a3-4954-8af7-7863bb5cfd86)
![image](https://github.com/edgexfoundry/edgex-examples/assets/107825627/19d1825e-566d-4b24-9bab-d2401d0cc72b)
Run in a few seconds and stop

My environment：
ubuntu20.04 with VMware workstation，edgex-compose-levski，edgex-examples-main

**Comment by bnevis-i** [comment] 2023-05-24 14:17
I don't know if this is the cause of your issue, but one of the errors about /dev/video0 is problematic:

The default compose files give access to device major number 81.  https://github.com/edgexfoundry/edgex-compose/blob/main/compose-builder/add-device-usb-camera.yml#L43

It looks like you are trying to use /dev/video0, which may not be mapped into the docker container or may have a different major device number.  See https://docs.docker.com/compose/compose-file/compose-file-v3/#devices for granting containers device access.

This is the limit of what I can help with.

**Comment by presatish** [comment] 2023-05-24 16:27
@Ianzhou397 We don't need to manually add the usb devices. The guide you are referring to is ancient, sorry about that. For the new upcoming Edgex release we have removed that guide from those docs. Please clean up your edgex and device service stack and use https://github.com/edgexfoundry/edgex-examples/tree/main/application-services/custom/camera-management#camera-management-example-app-service to install and let me know if you are still facing issues. With this the device will be auto discovered.

**Comment by ChristianDarr-personal** [comment] 2023-05-24 16:28
@Ianzhou397 See this documentation for updated instructions on how to use the usb device service: https://github.com/edgexfoundry/device-usb-camera/tree/v2.3.1/docs
The link you shared above is outdated and will be phased out with the upcoming release.

**Comment by Ianzhou397** [comment] 2023-05-24 16:49
@presatish I'm glad you followed my question.
That problem with manually adding the device may be due to a problem with my operation. After referencing the relatively recent documentation, I ran into a slight problem where the data would report an error and then run for a few seconds and then stop. I think it could be a mistake in model reasoning or an error in MQTT. I put the details up, please take a look. Thank you again for your interest.

**Comment by presatish** [comment] 2023-05-25 06:05
@Ianzhou397 Yes we recently started seeing error when we start a pipeline from the UI. According to my observation this error happens randomly sometimes, other times the pipelines run fine. We are trying to resolve this error. But I did not see at my end the error happening because of MQTT, it was more to do with the Edge-video-analytics microservice that we are using for doing inference. Please make sure you have configured MQTT properly by following step 7 from https://github.com/edgexfoundry/edgex-examples/tree/main/application-services/custom/camera-management#camera-management-example-app-service.

**Comment by Ianzhou397** [comment] 2023-05-25 06:41
@presatish I followed the docs exactly, and the MQTT configuration was fine, but I got the above error. Is your mistake the same as mine? I always reported an error and never succeeded. In addition, I reported an error when playing a video stream with mplayer.

**Comment by ajcasagrande** [comment] 2023-05-26 20:54
@Ianzhou397 From your [original images](https://github.com/edgexfoundry/edgex-examples/assets/107825627/0079ad4e-950e-4a06-97fe-b7b2c8547710) before you edited it, I can see the error lies in unable to communicate with mqtt broker.  I get the same error when I do not enable the mqtt broker for edgex. 

Please confirm that your mqtt-broker is running properly. Use `docker ps` and check for the `edgex-mqtt-broker` service. Make sure your `make run` or `make gen` commands include the `mqtt-broker` argument always. See step 1.6 [here](https://github.com/edgexfoundry/edgex-examples/tree/main/application-services/custom/camera-management#1-start-the-edgex-core-services-and-device-services)

**Comment by Ianzhou397** [comment] 2023-05-29 12:24
@ajcasagrande Glad to hear from you. From this command in step 1.6, I don't see information about the mqtt-broker parameters. I executed this command directly. Do you mean to add information about mqtt-broker after this command?
The edgex-mqtt-broker service is running normally.
![image](https://github.com/edgexfoundry/edgex-examples/assets/107825627/d58caad6-bdc2-4b42-a55a-2381d1d2f014)

**Comment by ajcasagrande** [comment] 2023-05-31 20:33
@Ianzhou397 no, if the `edgex-mqtt-broker` is running, that should be good enough. Make sure the example app is pointed to the correct hostname and port of the broker if not. Earlier builds of the service came with its own mqtt-broker in the evam docker-compose, and were run separate from edgex, so there may be some issues with the current integration.

If you have some logs of all of the services in text format I can take a look.

**Comment by presatish** [comment] 2023-06-02 17:00
@Ianzhou397 We have new Edgex release coming up, the release is done but the latest docs still need to be released. With this new release the example app should be more stable. Will keep you posted. Thanks.

**Comment by presatish** [comment] 2023-06-05 18:19
@Ianzhou397 You can now try with the latest release - https://github.com/edgexfoundry/edgex-examples/tree/main/application-services/custom/camera-management. Please do let us know if you are still facing issues.

**Comment by Ianzhou397** [comment] 2023-06-06 01:09
@presatish I didn't pay attention to this issue for the time being the other day, but I will reproduce this latest version as soon as possible in the next few days. Thank you for your help and reply.

**Comment by presatish** [comment] 2023-06-15 16:06
@Ianzhou397 This issue is open from few weeks, so please let us know if you have any more questions or we can close this. Thanks.

**Comment by presatish** [comment] 2023-06-20 19:53
Closing this issue as there were no more questions or comments.

**Closed by presatish** 2023-06-20 19:53 UTC
Labels: question
